### ISSUE TITLE
setState() called after dispose() in _PersistentTabViewState

### ISSUE THREAD

**Issue by kmalkan** [BilalShahid13/PersistentBottomNavBar#118]
When switching between tabs I encountered this error:

```
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for PersistentTabController:
setState() called after dispose(): _PersistentTabViewState#305f6(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1233:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1268:6)
#2      _PersistentTabViewState.initState.<anonymous closure> (package:persistent_bottom_nav_bar/persistent-tab-view.widget.dart:371:9)
#3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243:25)
#4      PersistentTabController.index= (package:persistent_bottom_nav_bar/models/persistent-nav-bar-scaffold.widget.dart:21:5)
...
The PersistentTabController sending notification was: Instance of 'PersistentTabController'
====================================================================================================
```

I believe the fix is to wrap [this line](https://github.com/BilalShahid13/PersistentBottomNavBar/blob/master/lib/persistent-tab-view.widget.dart#L371) with a check to see if the widget is mounted:

```
if (mounted) {
    setState(
        () => _currentIndex = _controller.index,
    );
}
```

**Comment by BilalShahid13** [comment]
Thank you for the suggestion. I'll update this in the next version.

**Comment by JaffaKetchup** [comment]
Any news on this?

**Comment by melwinlobo18** [comment]
@BilalShahid13 any update on this?

**Comment by JaffaKetchup** [comment]
Hi @melwinlobo18,
I'm not @BilalShahid13, however you can use my fork that fixes multiple issues by using this in pubspec.yaml instead of the real version:
```dart
    persistent_bottom_nav_bar:
        git:
          url: https://github.com/JaffaKetchup/PersistentBottomNavBar.git
```
You can even use some [cool new features I've added](https://github.com/JaffaKetchup/PersistentBottomNavBar/pull/1) by using the `ref` keyword:
```dart
    persistent_bottom_nav_bar:
        git:
          url: https://github.com/JaffaKetchup/PersistentBottomNavBar.git
          ref: AndroidScaffoldExperimental
```

**Comment by BilalShahid13** [comment]
Fixed

**Comment by melwinlobo18** [comment]
Awesome.  This issue is resolved for me. Thanks for the help @BilalShahid13 and @JaffaKetchup.
