### ISSUE TITLE
persistent_bottom_nav_bar: ^4.0.0 - type 'List<NavigatorObserver?>' is not a subtype of type 'List<NavigatorObserver>' in type cast

### ISSUE THREAD

**Issue by DhavalRKansara** [BilalShahid13/PersistentBottomNavBar#154]
**Code:** 
```
  @override
  Widget build(BuildContext context) {
    return PersistentTabView(
      context,
      controller: controller,
      screens: _buildScreens(),
      items: _navBarsItems(),
      confineInSafeArea: true,
      backgroundColor: Colors.grey.shade100,
      handleAndroidBackButtonPress: true,
      resizeToAvoidBottomInset: true,
      stateManagement: true,
      hideNavigationBarWhenKeyboardShows: true,
      popAllScreensOnTapOfSelectedTab: true,
      itemAnimationProperties: ItemAnimationProperties(
        // Navigation Bar's items animation properties.
        duration: Duration(milliseconds: 200),
        curve: Curves.ease,
      ),
      decoration: NavBarDecoration(
          border: Border(
        top: BorderSide(color: Colors.grey.shade400),
      )),
      screenTransitionAnimation: ScreenTransitionAnimation(
        // Screen transition animation on change of selected tab.
        animateTabTransition: true,
        curve: Curves.ease,
        duration: Duration(milliseconds: 200),
      ),
      navBarStyle: NavBarStyle.style6,

      onItemSelected: (index) {
        setState(() {
          _currentIndex = index;
        });
      }, // Choose the nav bar style with this property.
    );
  }

  List<Widget> _buildScreens() {
    return [SearchDrugUi(), More()];
  }
  
    List<PersistentBottomNavBarItem> _navBarsItems() {
    return [
      PersistentBottomNavBarItem(
        icon: Transform.scale(
            scale: 2.0,
            alignment: Alignment.topCenter,
            child: Image.asset('assets/icons/inventory.png',
                color: _currentIndex == 0
                    ? Theme.of(context).primaryColor
                    : Colors.grey)),
        title: (S.of(context).inventory),
        activeColorPrimary: Theme.of(context).primaryColor,
        inactiveColorPrimary: CupertinoColors.systemGrey,
        activeColorSecondary: Theme.of(context).primaryColor,
      ),
      PersistentBottomNavBarItem(
        icon: Transform.scale(
            scale: 2.0,
            alignment: Alignment.topCenter,
            child: Align(
              alignment: Alignment.bottomCenter,
              child: Image.asset('assets/icons/more.png',
                  color: _currentIndex == 1
                      ? Theme.of(context).primaryColor
                      : Colors.grey),
            )),
        title: (S.of(context).more),
        activeColorPrimary: Theme.of(context).primaryColor,
        inactiveColorPrimary: CupertinoColors.systemGrey,
        activeColorSecondary: Theme.of(context).primaryColor,
      )
    ];
  }

```

**Error:**
```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building CustomTabView(dirty, state: _CustomTabViewState#7d37e):
type 'List<NavigatorObserver?>' is not a subtype of type 'List<NavigatorObserver>' in type cast

The relevant error-causing widget was: 
  PersistentTabView file:///Users/dhavalkansara/Flutter%20Development/OfficeProjects/ips-on-go/lib/src/Modules/employee_dashboard/ui/employee_dashboard.dart:52:12
When the exception was thrown, this was the stack: 
#0      _CustomTabViewState.build (package:persistent_bottom_nav_bar/models/tab-view.widget.dart:52:38)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
```

**Comment by kirkcharlesniv** [comment]
Fails at `observers: _navigatorObservers as List<NavigatorObserver>,` on this LOC. [tab-view.widget.dart#L52](https://github.com/BilalShahid13/PersistentBottomNavBar/blob/master/lib/models/tab-view.widget.dart#L52)

**Comment by DhavalRKansara** [comment]
> Fails at `observers: _navigatorObservers as List<NavigatorObserver>,` on this LOC. [tab-view.widget.dart#L52](https://github.com/BilalShahid13/PersistentBottomNavBar/blob/master/lib/models/tab-view.widget.dart#L52)

How I can fixt it?

**Comment by kirkcharlesniv** [comment]
Hi, I made a fix which is available on https://github.com/BilalShahid13/PersistentBottomNavBar/pull/155 kindly test on your local then push to master, thanks!

**Comment by BilalShahid13** [comment]
Fixed in the latest release! :)
