### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by maitycyrus** [BilalShahid13/PersistentBottomNavBar#276]
`======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _PersistentTabViewState.popAllScreens (package:persistent_bottom_nav_bar/persistent-tab-view.widget.dart:732:45)
#1      _PersistentTabViewState.navigationBarWidget.<anonymous closure> (package:persistent_bottom_nav_bar/persistent-tab-view.widget.dart:601:25)
#2      _BottomNavStyle12State.build.<anonymous closure>.<anonymous closure> (package:persistent_bottom_nav_bar/nav-bar-styles/style-12-bottom-nav-bar.widget.dart:177:59)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#12     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#18     _invoke1 (dart:ui/hooks.dart:170:10)
#19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#a7603
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(184.0, 629.5)
  finalLocalPosition: Offset(28.8, 19.1)
  button: 1
  sent tap down
=======================`

**Comment by maitycyrus** [comment]
_contextList is non-nullable

**Comment by alexaung** [comment]
How do you solve this issue? I am also facing it

**Comment by kubawich** [comment]
@maitycyrus Hey, how did You fix this?

**Comment by hortigado** [comment]
I have the same problem
