### ISSUE TITLE
Tabbar inside PersistentBottomNavBar error when update child item from tabbar

### ISSUE THREAD

**Issue by khaitq7** [BilalShahid13/PersistentBottomNavBar#36]
Dear Bilal,
Thank for your library .
I see a problem when use both Tabbar inside PersistentBottomNavBar .

If I update view to child view (Item from Tabbar) & switch tab . 
It have error log ?
Please help give help me solve for that problem .
Thank you so much .

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during paint():
The method '-' was called on null.
Receiver: null
Tried calling: -(0.0)

The relevant error-causing widget was: 
  PersistentTabView file:///F:/Programer/workspace/PlayFun/playfun/lib/components/main_screen.dart:136:20
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
#2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
#3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
#4      InkFeature._paint (package:flutter/src/material/material.dart:623:26)
...
The following RenderObject was being processed when the exception was fired: _RenderInkFeatures#a3310
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=360.0, h=512.0)
...  size: Size(360.0, 512.0)
RenderObject: _RenderInkFeatures#a3310
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=360.0, h=512.0)
  size: Size(360.0, 512.0)
...  child: RenderFlex#b7afa NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=360.0, h=512.0)
...    size: Size(360.0, 512.0)
...    direction: vertical
...    mainAxisAlignment: start
...    mainAxisSize: max
...    crossAxisAlignment: center
...    verticalDirection: down
...    child 1: RenderConstrainedBox#7deeb relayoutBoundary=up1
...      parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=Infinity)
...      size: Size(360.0, 53.3)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=53.3)
...      child: RenderPadding#cb274 relayoutBoundary=up2
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=360.0, h=53.3)
...        size: Size(360.0, 53.3)
...        padding: EdgeInsets(0.0, 13.0, 0.0, 0.0)
...        textDirection: ltr
...        child: RenderFlex#878e6 relayoutBoundary=up3
...          parentData: offset=Offset(0.0, 13.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=360.0, h=40.3)
...          size: Size(360.0, 40.3)
...          direction: vertical
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          verticalDirection: down
...    child 2: RenderFlex#d94ca relayoutBoundary=up1 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 53.3); flex=1; fit=FlexFit.tight (can use size)
...      constraints: BoxConstraints(0.0<=w<=360.0, h=458.7)
...      size: Size(360.0, 458.7)
...      direction: vertical
...      mainAxisAlignment: start
...      mainAxisSize: max
...      crossAxisAlignment: center
...      verticalDirection: down
...      child 1: RenderPadding#d50cb relayoutBoundary=up2 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=Infinity)
...        size: Size(360.0, 56.4)
...        padding: EdgeInsets(0.0, 14.0, 0.0, 14.0)
...        textDirection: ltr
...        child: RenderConstrainedBox#0eff5 relayoutBoundary=up3 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 14.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=Infinity)
...          size: Size(360.0, 28.4)
...          additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=28.4)
...      child 2: RenderRepaintBoundary#2912d relayoutBoundary=up2
...        needs compositing
...        parentData: offset=Offset(0.0, 56.4); flex=1; fit=FlexFit.tight (can use size)
...        constraints: BoxConstraints(0.0<=w<=360.0, h=402.3)
...        layer: OffsetLayer#20116 DETACHED
...          engine layer: OffsetEngineLayer#aec9a
...          offset: Offset(0.0, 109.7)
...        size: Size(360.0, 402.3)
...        metrics: 78.4% useful (8 bad vs 29 good)
...        diagnosis: this is a useful repaint boundary and should be kept
...        child: RenderCustomPaint#e68b6 relayoutBoundary=up3
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=360.0, h=402.3)
...          size: Size(360.0, 402.3)
```
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by khaitq7** [comment]
I will update image error .
1. This tab (number 1 item from tabbar)

![image](https://user-images.githubusercontent.com/11715209/86080073-34c27a80-babc-11ea-9a18-d2afc928a8b6.png)

2. Switch to number 3 item in tabbar 
![image](https://user-images.githubusercontent.com/11715209/86080119-5459a300-babc-11ea-85dc-84e09f17e386.png)

3. Change state & update view to this tab .
![image](https://user-images.githubusercontent.com/11715209/86080150-69cecd00-babc-11ea-92de-30acbced72b6.png)

4. Switch to tab item number 1.
![image](https://user-images.githubusercontent.com/11715209/86080196-80752400-babc-11ea-8d21-440cdb522757.png)

=> It is white screen

**Comment by khaitq7** [comment]
I found the problem .
In the child view , I changed Ink & InkWell to another component . It's well done .

**Comment by BilalShahid13** [comment]
That's great. Sorry for not answering on time. I'm a bit busy these days.
